package com.key_stone.Enum;

public enum Permissions {

	LOGIN,LOGOUT,
	
	CREATE_USER,VIEW_USER,UPDATE_USER,DELETE_USER,
	
	CREATE_CUSTOMER,VIEW_CUSTOMER,UPDATE_CUSTOMER,DELETE_CUSTOMER,
	
	CREATE_SITE,VIEW_SITE,UPDATE_SITE,DELETE_SITE,
	
	CREATE_WO,VIEW_WO,UPDATE_WO,ASSIGN_WO,CANCEL_WO,CLOSE_WO,DELETE_WO,
	
	START_WORK,HOLD_WORK,RESUME_WORK,COMPLETE_WORK,
	
	ADD_PARTS,VIEW_PARTS,UPDATE_PARTS,DELETE_PARTS,USE_PARTS,
	
	ADD_TIME_LOGS,VIEW_TIME_LOGS,
	
	VIEW_DASHBOARD,VIEW_RECORDS,
	
	SEND_NOTIFICATION,
	
	RAISE_REQUEST,VIEW_OWN_REQUEST
	
}
